# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - agora

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore
      
      - name: Clean old build outputs
        run: |
          if (Test-Path published) { Remove-Item -Recurse -Force published }
          if (Test-Path "Agora.Onboarding\obj") { Remove-Item -Recurse -Force "Agora.Onboarding\obj" }
          if (Test-Path "Agora.Onboarding\bin") { Remove-Item -Recurse -Force "Agora.Onboarding\bin" }

      - name: Publish to folder
        run: "msbuild AgoraMember.sln /p:Configuration=Release /t:Build;WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=published"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/



  deploy:
    runs-on: windows-latest
    needs: build
    
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: downloaded
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agora'
          slot-name: 'Production'
          package: downloaded/
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A9AB9F54EEC4449DAB1253EFA5A137E4 }}
